### ISSUE TITLE
Provide sample UE project

### ISSUE THREAD

**Issue by delebash** [PoseAI/PoseCameraAPI#2]
It would be great to have sample projects with both UE, Metahuman, and Mixamo characters so we can get started quickly without having to go through the manual setup process.

**Comment by PoseAI** [comment]
This was already in the works but we have just posted a first sample and it can be found in the repository here:
[https://github.com/PoseAI/PoseCameraAPI/tree/main/UnrealEngineAPI/ExampleProject4.26](https://github.com/PoseAI/PoseCameraAPI/tree/main/UnrealEngineAPI/ExampleProject4.26)

We can't include characters (apart from the UE4 Mannequin) due to licensing but we include the skeleton for Mixamo and anim blueprints so it is pretty easy to import a downloaded character  (instructions are in the tutorial in the example).   MetaHuman rigs are more complex and you will need to follow the instructions.

**Comment by delebash** [comment]
Thanks, I built the plugin in blank UE5 project with no problems.  However the app on my phone does not seem to work, the image is supposed to turn blue when it dectects your body but mine stays white and no data seems to be transmited to UE.  Is there a way in UE to see if any data is being sent to Live Link from my iPhone app.  I am using an iPhone 6s and I know it is not officially supported but you noted that some people had it working on your website.  Thanks for the update with the project I will check it out.  Love the project great work you all.

**Comment by PoseAI** [comment]
Yes, in UE4 in the bottom livelink panel your source should have a green light when transmitting.  If the body stays grey on your phone than it is not detecting you.

Could you be too close to your phone?  Ideally the camera should have an unobstructed view of your head to your hips (or to feet for Room/Portrait mode).

Also, the oldest phone we tried was an iPhone 7, not the iPhone 6, and the only other early tester on an iPhone 7 couldn't get it to work on that chipset (I believe that got some very jerky animation).
