### ISSUE TITLE
Add_on for Blender

### ISSUE THREAD

**Issue by saibai** [PoseAI/PoseCameraAPI#23]
Ciao
Finally, I succeeded in writing a python add-on for Blender. It connects and responds, and I implemented the ability to manage the "handshake" parameters, the ability to record tower values... in short, everything works as it should. The only big problem is that I can't set an "Armature" and its "Bones" in any way. I tried with your FBX of Unity, Mixamo, metarig, but every time there is something wrong... I'm creating this add-on for myself so that I can animate my characters based on the Metarig Skeleton. Do you have any suggestions? If you want, I can send you the add-on privately and you can test it directly.

**Comment by DatanIMU** [comment]
Hi PoseAI，

thanks for your high quality code.

You have said "A Blender plugin is on our "someday" to do list." Are you on the way to do it?

**Comment by PoseAI** [comment]
> Ciao Finally, I succeeded in writing a python add-on for Blender. It connects and responds, and I implemented the ability to manage the "handshake" parameters, the ability to record tower values... in short, everything works as it should. The only big problem is that I can't set an "Armature" and its "Bones" in any way. I tried with your FBX of Unity, Mixamo, metarig, but every time there is something wrong... I'm creating this add-on for myself so that I can animate my characters based on the Metarig Skeleton. Do you have any suggestions? If you want, I can send you the add-on privately and you can test it directly.

Sorry for delay, we missed the issue notification somehow!
It seems you are asking a specific Blender issue re setting the armature and the bones, rather than a PoseAI issue.
We are pretty stretched right now and the one team member who is proficient at Blender has no capacity to delve into this currently.

You may have better luck on a Blender forum.  

If I misunderstood, our engine/app takes in a "rig" string and then uses our retargetting from our research model to the specified rig to determine the rotation of the joint for output.  Each game engine or program has their own finicky way of modelling skeletons, and it was painful figuring this out for Unreal (which changed at somepoint during our development when they promoted LiveLink forcing a total rewrite) and Unity.

**Comment by PoseAI** [comment]
> Hi PoseAI，
> 
> thanks for your high quality code.
> 
> You have said "A Blender plugin is on our "someday" to do list." Are you on the way to do it?

Our focus has still be on our core engine for licensing, rather than supporting creators.  We are hoping to have capacity to release a Windows product for creators before the summer, at which point we will revisit the priority list and look at support for Blender/Maya/Autodesk
