### ISSUE TITLE
Since version 1.4,body is twisting in unreal engine

### ISSUE THREAD

**Issue by GinjiGinji** [PoseAI/PoseCameraAPI#25]
![スクリーンショット (41)](https://user-images.githubusercontent.com/121884758/222769234-96a69a79-41dd-4738-a605-3aba54d61ef4.png)

Hi!. Since version 1.4, when I run pose ai in unreal engine, the body twists as shown in the image. How can I fix this?

**Comment by PoseAI** [comment]
Hi, in the handshake there is a tick box which can rotate the lower body 180 degrees.  Either tick or on or off (opposite of what you have now) and it should solve the problem.We added that to handle different setups (some users only using character blueprint, some users using animation blueprints with blendnodes overriding lower body)On 3 Mar 2023, at 16:16, GinjiGinji ***@***.***> wrote:﻿

Hi!. Since version 1.4, when I run pose ai in unreal engine, the body twists as shown in the image. How can I fix this?

**Comment by GinjiGinji** [comment]
Hi! Thank you very much!
