### ISSUE TITLE
Can you update Readme to describe the update by 3.0version?

### ISSUE THREAD

**Issue by DatanIMU** [PoseAI/PoseCameraAPI#29]
I have another thing, how can I cancel the breathing animation of a character in a still state? No matter how I maintain a still position now, the character of Unity is swaying slightly to the left and right. I guess this is the breathing animation effect you added. How can I prohibit it?

**Comment by PoseAI** [comment]
We do not add a breathing animation effect ourselves, so that would be from the game engine:
For the swaying, that may not be the animation but caused by the in game camera setting: the Cinemachine Virtual Camera class has a noise setting.  For our demo I think we just left the default Unity example which is something like "handheld mild" setting which creates some sway.
If there is a breathing effect, that would be caused by the default animation (usually an "Idle" animation) in the Animation Controller, as our scripts modify the base animation during the IK pass, but a breathing effect on the mesh would be additive.  So if you had a perfectly stable underlying animation, our stream should not impact.


For the readme comment, we know we have fallen behind on some of the public documentation.  Definitely on our todo list for later this summer once we clear some higher priority items.  I will leave this open as a reminder to ourselves to catch up.
