### ISSUE TITLE
Json deserialize failed, shown in UE5.0.4

### ISSUE THREAD

**Issue by DatanIMU** [PoseAI/PoseCameraAPI#31]
Using Live link Face App(ARkit mode)，iphone13. Use poseAI plugin in UE market.

connect UE5.04 live link.

it shows:
（10,141） PoseAI: failed to deserialize json object from 192.168.3.5:50531, Invalid Json Token. Line: 1 Ch: 1

Can you check it?

**Comment by PoseAI** [comment]
hi

1. Epic's policy on plugins is to only update/support the most recent 3, so that would be 5.1, 5.2, and 5.3 currently, but not 5.0. So any changes we make to older versions to deal with API changes don't get updated on Epic's marketplace.  As you mention 5.04 we can't be sure what exactly you have installed, as it could be from Github or it could be the stale version Epic keeps on their server.   You could try building with the plugin here from github to see if that resolves, as we believe we backported any necessary changes to the 5.0 version here on Github (given the Epic policy we don't test much on the older versions). 

2.  can you tell us which packet format you were using? we have a verbose setting (mainly for debugging) and a compact one.  On some routers (rare but apparently more common in china at least) the verbose setting may get truncated due to length.  If you are having issues you can try flipping that setting in the handshake to see if it resolves.
