### ISSUE TITLE
Movie Render Queue

### ISSUE THREAD

**Issue by michela** [PoseAI/PoseCameraAPI#7]
Is this compatible with UE4 Movie Render Queue? I have a Sequence in my level that plays back a poseai capture fine in Play mode, not Editor mode. But the character is entirely missing from renders

**Comment by PoseAI** [comment]
Hi, we don’t have any in-house experience with that aspect of UE4 so the specific use case is untested.  

if you are playing back a precaptured fbx than it should work fine.  Maybe check what value was recorded for root position/hips if your character is missing? (Could your character just be moved well off camera?)

Otherwise if you are combining them live, if UE4’s LiveLink plug-in is compatible with the MovieRender Queue than I would expect our plug-in to work (as we are just providing a LiveLink Source).

**Comment by PoseAI** [comment]
Closing due to lack of reply.
